// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgsavnlyathtlvrevtjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnc2F2bmx5YXRodGx2cmV2dGpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NjI1MzMsImV4cCI6MjA3MTAzODUzM30.F8KXmmqb4dqgZJJSqGb0O9fpgUY9WIRnVe7ZanquWGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});